name: PaperRank
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07
  - certifi=2018.4.16
  - openssl=1.0.2o
  - pip=10.0.1
  - python=3.6.5
  - setuptools=39.2.0
  - sqlite=3.24.0
  - tk=8.6.7
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - astroid==1.6.5
    - isort==4.3.4
    - lazy-object-proxy==1.3.1
    - mccabe==0.6.1
    - pylint==1.9.2
    - six==1.11.0
    - wrapt==1.10.11

