name: PaperRank
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07
  - certifi=2018.4.16
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.0.2o
  - pip=10.0.1
  - python=3.6.5
  - readline=7.0
  - setuptools=39.2.0
  - sqlite=3.24.0
  - tk=8.6.7
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - alabaster==0.7.11
    - argh==0.26.2
    - astroid==1.6.5
    - atomicwrites==1.1.5
    - attrs==18.1.0
    - babel==2.6.0
    - chardet==3.0.4
    - docutils==0.14
    - et-xmlfile==1.0.1
    - idna==2.7
    - imagesize==1.0.0
    - isort==4.3.4
    - jdcal==1.4
    - jinja2==2.10
    - lazy-object-proxy==1.3.1
    - livereload==2.5.2
    - markupsafe==1.0
    - mccabe==0.6.1
    - more-itertools==4.2.0
    - numpy==1.15.0
    - openpyxl==2.5.4
    - packaging==17.1
    - pandas==0.23.3
    - pathtools==0.1.2
    - pep8==1.7.1
    - pluggy==0.6.0
    - port-for==0.3.1
    - py==1.5.4
    - pycodestyle==2.4.0
    - pygments==2.2.0
    - pylint==1.9.2
    - pyparsing==2.2.0
    - python-dateutil==2.7.3
    - pytz==2018.5
    - pyyaml==3.13
    - redis==2.10.6
    - requests==2.19.1
    - scipy==1.1.0
    - six==1.11.0
    - snowballstemmer==1.2.1
    - sphinxcontrib-websupport==1.1.0
    - tornado==5.0.2
    - urllib3==1.23
    - watchdog==0.8.3
    - wrapt==1.10.11
    - xmltodict==0.11.0

